from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from datetime import datetime
from pathlib import Path

try:
    import pandas as pd
except ModuleNotFoundError:  # pragma: no cover - fallback runtime path
    pd = None


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Simple long-only backtest from signal CSV.")
    parser.add_argument("--input", required=True, help="Signal CSV generated by run_stock_market_test.py")
    parser.add_argument("--output", required=True, help="Path for summary metrics CSV")
    parser.add_argument("--price-column", default="close", help="Price column to use")
    parser.add_argument("--ticker-column", default="ticker", help="Ticker column")
    return parser.parse_args()


def _target_exposure(signal: str) -> float:
    action = str(signal).upper()
    if action == "BUY":
        return 1.0
    if action in {"SELL", "REDUCE"}:
        return 0.5
    if action == "EXIT":
        return 0.0
    return 1.0


def _run_with_pandas(args: argparse.Namespace) -> None:
    df = pd.read_csv(args.input)

    results: list[dict[str, float | str]] = []
    for ticker, group in df.groupby(args.ticker_column):
        g = group.copy().reset_index(drop=True)
        if "timestamp" in g.columns:
            g["timestamp"] = pd.to_datetime(g["timestamp"], errors="coerce", utc=True)
            g = g.sort_values("timestamp").reset_index(drop=True)

        g["price"] = pd.to_numeric(g[args.price_column], errors="coerce")
        g = g.dropna(subset=["price"])
        if len(g) < 2:
            continue

        signal_series = g["trading_signal"] if "trading_signal" in g.columns else "HOLD"
        g["ret"] = g["price"].pct_change().fillna(0.0)
        g["exposure"] = signal_series.map(_target_exposure).fillna(1.0)
        g["strat_ret"] = g["ret"] * g["exposure"].shift(1).fillna(1.0)

        equity = (1.0 + g["strat_ret"]).cumprod()
        running_peak = equity.cummax()
        drawdown = (equity / running_peak) - 1.0

        total_return = float(equity.iloc[-1] - 1.0)
        win_rate = float((g["strat_ret"] > 0).mean())
        max_drawdown = float(drawdown.min())

        results.append(
            {
                "ticker": str(ticker),
                "bars": int(len(g)),
                "total_return": total_return,
                "win_rate": win_rate,
                "max_drawdown": max_drawdown,
            }
        )

    pd.DataFrame(results).to_csv(args.output, index=False)


def _parse_ts(text: str) -> float:
    value = str(text)
    if value.endswith("Z"):
        value = value[:-1] + "+00:00"
    return datetime.fromisoformat(value).timestamp()


def _run_without_pandas(args: argparse.Namespace) -> None:
    with Path(args.input).open("r", encoding="utf-8", newline="") as fh:
        rows = list(csv.DictReader(fh))

    groups: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        groups[str(row.get(args.ticker_column, ""))].append(row)

    results: list[dict[str, float | str | int]] = []
    for ticker, group in groups.items():
        def _sort_key(item: dict[str, str]) -> float:
            ts = item.get("timestamp")
            if ts:
                try:
                    return _parse_ts(ts)
                except ValueError:
                    return 0.0
            return 0.0

        ordered = sorted(group, key=_sort_key)
        cleaned: list[dict[str, float | str]] = []
        for item in ordered:
            try:
                price = float(item.get(args.price_column, ""))
            except (TypeError, ValueError):
                continue
            cleaned.append({"price": price, "signal": str(item.get("trading_signal", "HOLD"))})

        if len(cleaned) < 2:
            continue

        strat_rets: list[float] = []
        prev_exposure = 1.0
        prev_price = cleaned[0]["price"]
        equity = 1.0
        running_peak = 1.0
        max_drawdown = 0.0

        for row in cleaned:
            price = float(row["price"])
            ret = 0.0 if prev_price == 0.0 else (price / prev_price) - 1.0
            strat_ret = ret * prev_exposure
            equity *= 1.0 + strat_ret
            running_peak = max(running_peak, equity)
            max_drawdown = min(max_drawdown, (equity / running_peak) - 1.0)
            strat_rets.append(strat_ret)

            prev_exposure = _target_exposure(str(row["signal"]))
            prev_price = price

        positive = sum(1 for value in strat_rets if value > 0)
        results.append(
            {
                "ticker": ticker,
                "bars": len(cleaned),
                "total_return": equity - 1.0,
                "win_rate": positive / len(strat_rets),
                "max_drawdown": max_drawdown,
            }
        )

    with Path(args.output).open("w", encoding="utf-8", newline="") as fh:
        fieldnames = ["ticker", "bars", "total_return", "win_rate", "max_drawdown"]
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(results)


def main() -> None:
    args = parse_args()
    if pd is not None:
        _run_with_pandas(args)
    else:
        _run_without_pandas(args)


if __name__ == "__main__":
    main()
