from __future__ import annotations

import argparse

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Simple long-only backtest from signal CSV.")
    parser.add_argument("--input", required=True, help="Signal CSV generated by run_stock_market_test.py")
    parser.add_argument("--output", required=True, help="Path for summary metrics CSV")
    parser.add_argument("--price-column", default="close", help="Price column to use")
    parser.add_argument("--ticker-column", default="ticker", help="Ticker column")
    return parser.parse_args()


def _target_exposure(signal: str) -> float:
    action = str(signal).upper()
    if action == "BUY":
        return 1.0
    if action in {"SELL", "REDUCE"}:
        return 0.5
    if action == "EXIT":
        return 0.0
    return 1.0


def main() -> None:
    args = parse_args()
    df = pd.read_csv(args.input)

    results: list[dict[str, float | str]] = []
    for ticker, group in df.groupby(args.ticker_column):
        g = group.copy().reset_index(drop=True)
        if "timestamp" in g.columns:
            g["timestamp"] = pd.to_datetime(g["timestamp"], errors="coerce", utc=True)
            g = g.sort_values("timestamp").reset_index(drop=True)

        g["price"] = pd.to_numeric(g[args.price_column], errors="coerce")
        g = g.dropna(subset=["price"])
        if len(g) < 2:
            continue

        signal_series = g["trading_signal"] if "trading_signal" in g.columns else "HOLD"
        g["ret"] = g["price"].pct_change().fillna(0.0)
        g["exposure"] = signal_series.map(_target_exposure).fillna(1.0)
        g["strat_ret"] = g["ret"] * g["exposure"].shift(1).fillna(1.0)

        equity = (1.0 + g["strat_ret"]).cumprod()
        running_peak = equity.cummax()
        drawdown = (equity / running_peak) - 1.0

        total_return = float(equity.iloc[-1] - 1.0)
        win_rate = float((g["strat_ret"] > 0).mean())
        max_drawdown = float(drawdown.min())

        results.append(
            {
                "ticker": str(ticker),
                "bars": int(len(g)),
                "total_return": total_return,
                "win_rate": win_rate,
                "max_drawdown": max_drawdown,
            }
        )

    pd.DataFrame(results).to_csv(args.output, index=False)


if __name__ == "__main__":
    main()
