#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build a lightweight FD001 validation report from existing JSONL outputs."
    )
    parser.add_argument(
        "--input-jsonl",
        type=Path,
        default=Path("outputs/fd001_validation/fd001_validation_full.jsonl"),
        help="Existing replay output JSONL generated by run_fd001_demo.py.",
    )
    parser.add_argument(
        "--summary-csv",
        type=Path,
        default=Path("reports/fd001_validation/fd001_validation_unit_summary.csv"),
        help="Small per-unit summary CSV output path.",
    )
    parser.add_argument(
        "--report-md",
        type=Path,
        default=Path("reports/fd001_validation/fd001_validation_report.md"),
        help="Markdown report output path.",
    )
    return parser.parse_args()


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def _risk_score(result: dict[str, Any]) -> float:
    risk = result.get("risk_assessment") if isinstance(result.get("risk_assessment"), dict) else {}
    raw = risk.get("risk_score", 0.0)
    try:
        return float(raw)
    except (TypeError, ValueError):
        return 0.0


def _risk_level(result: dict[str, Any]) -> str:
    risk = result.get("risk_assessment") if isinstance(result.get("risk_assessment"), dict) else {}
    level = str(risk.get("current_risk_level") or risk.get("risk_level") or "UNKNOWN")
    return level.upper()


def _decision_available(result: dict[str, Any]) -> bool:
    decision = result.get("decision") if isinstance(result.get("decision"), dict) else {}
    status = decision.get("status") if isinstance(decision.get("status"), dict) else {}
    return bool(status.get("available"))


def _first_cycle_matching(rows: list[dict[str, Any]], predicate) -> int | None:
    for row in rows:
        if predicate(row):
            return int(row.get("cycle", 0))
    return None


def _build_unit_summary(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    by_unit: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_unit[int(row["unit_id"])].append(row)

    out: list[dict[str, Any]] = []
    for unit_id in sorted(by_unit):
        unit_rows = sorted(by_unit[unit_id], key=lambda r: int(r.get("cycle", 0)))
        levels = Counter(_risk_level(row) for row in unit_rows)
        out.append(
            {
                "unit_id": unit_id,
                "cycles_processed": len(unit_rows),
                "first_medium_or_high_cycle": _first_cycle_matching(
                    unit_rows, lambda r: _risk_level(r) in {"MEDIUM", "HIGH"}
                ),
                "first_decision_cycle": _first_cycle_matching(unit_rows, _decision_available),
                "peak_risk_score": round(max(_risk_score(row) for row in unit_rows), 6),
                "mean_risk_score": round(mean(_risk_score(row) for row in unit_rows), 6),
                "high_count": levels.get("HIGH", 0),
                "medium_count": levels.get("MEDIUM", 0),
                "low_count": levels.get("LOW", 0),
            }
        )
    return out


def _write_summary_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    headers = [
        "unit_id",
        "cycles_processed",
        "first_medium_or_high_cycle",
        "first_decision_cycle",
        "peak_risk_score",
        "mean_risk_score",
        "high_count",
        "medium_count",
        "low_count",
    ]
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=headers)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def _write_markdown_report(path: Path, source: Path, unit_summary: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    total_cycles = sum(int(row["cycles_processed"]) for row in unit_summary)
    first_trigger_cycles = [
        int(row["first_medium_or_high_cycle"])
        for row in unit_summary
        if row["first_medium_or_high_cycle"] is not None
    ]
    decision_cycles = [
        int(row["first_decision_cycle"])
        for row in unit_summary
        if row["first_decision_cycle"] is not None
    ]

    lines = [
        "# FD001 validation report (lightweight)",
        "",
        f"- Source JSONL: `{source}`",
        f"- Units summarized: **{len(unit_summary)}**",
        f"- Cycles summarized: **{total_cycles}**",
        (
            f"- Mean first MEDIUM/HIGH cycle: **{round(mean(first_trigger_cycles), 2)}**"
            if first_trigger_cycles
            else "- Mean first MEDIUM/HIGH cycle: **n/a**"
        ),
        (
            f"- Mean first decision-available cycle: **{round(mean(decision_cycles), 2)}**"
            if decision_cycles
            else "- Mean first decision-available cycle: **n/a**"
        ),
        "",
        "## Notes",
        "- This script reads existing replay outputs only.",
        "- It writes summary-level artifacts (CSV + Markdown) and avoids raw per-cycle dumps.",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    args = parse_args()
    if not args.input_jsonl.exists():
        raise FileNotFoundError(
            f"Input JSONL does not exist: {args.input_jsonl}. Run run_fd001_demo.py locally first."
        )

    rows = _read_jsonl(args.input_jsonl)
    if not rows:
        raise ValueError(f"Input JSONL is empty: {args.input_jsonl}")

    unit_summary = _build_unit_summary(rows)
    _write_summary_csv(args.summary_csv, unit_summary)
    _write_markdown_report(args.report_md, args.input_jsonl, unit_summary)

    print(f"source_rows={len(rows)}")
    print(f"units={len(unit_summary)}")
    print(f"summary_csv={args.summary_csv}")
    print(f"report_md={args.report_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
